### ISSUE TITLE
db

### ISSUE THREAD

**Issue by perish6368** [nabilfarhann/Vidhub#1]
i need help with the db every time i put in my db login like this
![image](https://user-images.githubusercontent.com/79872179/119552245-5620fa80-bd4f-11eb-8dfa-77b7ef3d1336.png)
 it says this 
![image](https://user-images.githubusercontent.com/79872179/119552331-6cc75180-bd4f-11eb-862f-ee3ccd3e2a6f.png)

**Comment by tellesdaxten** [comment]
Try this:

$con = new PDO("mysql:host=localhost;dbname=vidhub", 'dbusername', 'dbpassword');

**Comment by nabilfarhann** [comment]
> Try this:
> 
> $con = new PDO("mysql:host=localhost;dbname=vidhub", 'dbusername', 'dbpassword');
Yes, this is the correct way if you want to run it on your local machine
